### ISSUE TITLE
Add country code spinner before phone number edit text.

### ISSUE THREAD

**Issue by roshniRam** [NJACKWinterOfCode/WhatsApp-Direct-Message#1]
Add a drop-down containing the list of country codes on the left side of phone number edit text.

**Comment by 27vinayvyas** [comment]
Ma'am i have made a PR and a request for same more related changes . If u could just see and verify if i could work on that issues or not??

**Comment by 27vinayvyas** [comment]
Also if there is something inappropriate in the code, please let me know son that i can improve on it
Thnx in advance @roshniRam

**Comment by roshniRam** [comment]
Yeah

**Comment by 27vinayvyas** [comment]
what does this mean @roshniRam  !! 
Can i work on those suggested changes  or not??
