### ISSUE TITLE
Check the user input is in valid format.

### ISSUE THREAD

**Issue by roshniRam** [NJACKWinterOfCode/WhatsApp-Direct-Message#12]
Once the user inputs any number before redirecting it to WhatsApp check whether the number is in a valid format or not. Check whether it has country code followed by the phone number of appropriate length corresponding to the country.

**Comment by amartya-mondal** [comment]
Shall we need to check the validity of the country code?

**Comment by amangrobo** [comment]
It checks the number format now #27
