### ISSUE TITLE
Change app theme.

### ISSUE THREAD

**Issue by roshniRam** [NJACKWinterOfCode/WhatsApp-Direct-Message#2]
colorPrimary - #0091EA
colorPrimaryDark - #000000
Change the color theme of the app by pasting the above-given color codes in appropriate .xml of the res folder.

**Comment by rob729** [comment]
I would like to work on this issue

**Comment by rob729** [comment]
@roshniRam  I guess one has to first claim an issue before sending a PR for an issue.

**Comment by roshniRam** [comment]
Yes

**Comment by rob729** [comment]
@roshniRam then how can you merge this pull request because he didn't claimed this issue and  I asked first to claim this issue ?
