### ISSUE TITLE
Create a toggle for theme.

### ISSUE THREAD

**Issue by roshniRam** [NJACKWinterOfCode/WhatsApp-Direct-Message#85]
From the menu remove light theme option and create a toggle button for dark theme. If it is enabled the app will have dark theme and the default theme will be light theme.

**Comment by amartya-mondal** [comment]
I am working on it

**Comment by roshniRam** [comment]
@amartya-mondal  whats the status?

**Comment by amartya-mondal** [comment]
Will be making the pr soon. Sorry for the delay..
